apiVersion: v1
kind: Pod
metadata:
  name: pod-dangereux
  namespace: namespace-pss
spec:
  containers:
  - name: app
    image: nginx
    securityContext:
      privileged: false
      allowPrivilegeEscalation: false        
      runAsUser: 1000 
      runAsNonRoot: true 
      capabilities:
        drop:
          - ALL
        add:
          - NET_BIND_SERVICE
      seccompProfile:
        type: RuntimeDefault
               
  #   volumeMounts:
  #   - name: host-root
  #     mountPath: /host
  # volumes:
  # - name: host-root
  #   hostPath:
  #     path: /      