apiVersion: v1
kind: Namespace
metadata:
  name: namespace-pss
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/audit: restricted

---

