apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-content-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
        client: ghost-mysql
    spec:
      containers:
      - name: ghost
        image: ghost:5-alpine
        env:
        - name: database__client
          value: "mysql"
        - name: database__connection__host
          value: "mysql-service"
        - name: database__connection__port
          value: "3306"
        - name: database__connection__user
          value: "ghost"
        - name: database__connection__password
          value: "ghostpassword"
        - name: database__connection__database
          value: "ghost"
        - name: url
          value: "http://localhost:30080"
        - name: NODE_ENV
          value: "production"
        ports:
        - containerPort: 2368
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 2368
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 2368
          initialDelaySeconds: 30
          periodSeconds: 5
        volumeMounts:
        - name: ghost-content
          mountPath: /var/lib/ghost/content
      volumes:
      - name: ghost-content
        persistentVolumeClaim:
          claimName: ghost-content-pvc