apiVersion: v1
kind: Pod
metadata:
  name: with-mutliple-container
  labels:
    name: with-mutliple-container
spec:
  # Init Containers are executed before the main containers and can be used for setup tasks
  initContainers:
  - name: init-myservice
    image: busybox
    command: ['sh', '-c', 'echo The app is starting; sleep 5']
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
  # Define the main container and sidecar containers
  containers:
  - name: main-container
    image: nginx:latest
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
  - name: sidecar-container
    image: busybox
    command: ['sh', '-c', 'echo Sidecar container running; sleep 3600']
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
  # Define the pod's resource limits and requests
