apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginxprobes
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    lifecycle:
      postStart:
        exec:
          command: ["sh", "-c", "echo 'Post-start hook executed'; sleep 5"]
      
      preStop:
        exec:
          command: ["sh", "-c", "echo 'Pre-stop hook executed'; sleep 5"]
      
    ports:
      - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
    readinessProbe:
      httpGet: 
        path: /test
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
    startupProbe:
      httpGet: 
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
  terminationGracePeriodSeconds: 30
