apiVersion: v1
kind: Pod
metadata:
  name: myapod
  labels:
    name: myapod
spec:
  containers:
  - name: myapod
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
