apiVersion: v1
kind: Secret
metadata:
  name: app-config-secret
  labels:
    type: application-config
type: Opaque
data:
  # Données encodées en base64 (echo -n "valeur" | base64)
  database_url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAbG9jYWxob3N0OjU0MzIvbXlkYg==  # postgresql://user:password@localhost:5432/mydb
  api_key: c2stMTIzNDU2Nzg5MGFiY2RlZg==  # sk-1234567890abcdef
  jwt_secret: bXktc3VwZXItc2VjcmV0LWp3dC1rZXk=  # my-super-secret-jwt-key
  debug_mode: dHJ1ZQ==  # true