apiVersion: v1
kind: Pod
metadata:
  name: persistent-demo
spec:
  containers:
  - name: data-writer
    image: alpine:latest
    command: ["/bin/sh"]
    args:
      - -c
      - |
        echo "=== Écriture de données persistantes ==="
        echo "Données persistantes créées le $(date)" > /data/persistent-file.txt
        echo "Session: $$" >> /data/persistent-file.txt
        
        # Simulation d'une application qui écrit continuellement
        while true; do
          echo "Log: $(date)" >> /data/application.log
          sleep 10
        done
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  
  volumes:
  # Utilisation du PVC
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: data-pvc
  
    
 