apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  # Capacité du volume
  capacity:
    storage: 1Gi
  
  # Modes d'accès
  accessModes:
    - ReadWriteOnce  # Un seul Pod peut écrire
  
  # Politique de récupération
  persistentVolumeReclaimPolicy: Retain
  
  # Classe de stockage (optionnel)
  storageClassName: local-path

  local:
    path: /tmp/host-path
  
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3d-storage-demo-agent-1