apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: default
subjects:
# Référence au ServiceAccount
- kind: ServiceAccount
  name: demo-user
  namespace: default
roleRef:
  # Référence au Role créé précédemment
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: CluserRoleBinding
# metadata:
#   name: read-pods-cluster
#   namespace: default
# subjects:
# # Référence au ServiceAccount
# - kind: ServiceAccount
#   name: demo-user
#   namespace: default
# roleRef:
#   # Référence au Role créé précédemment
#   kind: ClusterRole
#   name: cluster-admin
#   apiGroup: rbac.authorization.k8s.io