stages:
  - build
  - release
  - config

build go version:
  stage: build
  image: jdrouet/docker-with-buildx:20.10.19-0.9.1
  services:
    - docker:20.10-dind
  script:
    - echo ${VOTING_DOCKERHUB_TOKEN} | docker login -u voting --password-stdin
    - docker buildx create --use
    - echo docker buildx build --platform linux/amd64 -t voting/${CI_PROJECT_NAME}:${CI_COMMIT_TAG} -t voting/${CI_PROJECT_NAME}:latest ./src --push
    - docker buildx build --platform linux/amd64 -t voting/${CI_PROJECT_NAME}:${CI_COMMIT_TAG} -t voting/${CI_PROJECT_NAME}:latest ./src --push
    
  only:
    - tags

release:
  image: node:20
  stage: release
  only:
    refs:
      - main
  script:
    - touch CHANGELOG.md
    - npm install @semantic-release/gitlab @semantic-release/exec @semantic-release/changelog
    - npx semantic-release
  artifacts:
    paths:
      - CHANGELOG.md

update config:
  stage: config
  image: lucj/ci:1.0
  script: |
    git config --global user.email "devops@techwhale.io"
    git config --global user.name "TechWhale DevOps"
    git clone --depth 1 https://gitlab-ci-token:${TECHWHALE_GITLAB_TOKEN}@gitlab.com/techwhale/config-argocd.git
    cd config-argocd/configs/votingapp
    yq -i ".${CI_PROJECT_NAME}.tag=\"${CI_COMMIT_TAG}\"" ./values-demo.yaml
    yq -i ".${CI_PROJECT_NAME}.tag=\"${CI_COMMIT_TAG}\"" ./values-prod.yaml
    git add ./values-demo.yaml ./values-prod.yaml
    cat ./values-demo.yaml ./values-prod.yaml
    git commit -m "Update ${CI_PROJECT_NAME} related tag with $CI_COMMIT_TAG in values files"
    git push origin main
  only:
    - tags