apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: postgres
spec:
  containers:
  - name: postgres
    image: postgres:15
    env:
    - name: POSTGRES_USER
      value: "demo"
    - name: POSTGRES_PASSWORD
      value: "demo"
    - name: POSTGRES_DB
      value: "testdb"
    - name: PGDATA
      value: "/var/lib/postgresql/data/pgdata"
    ports:
    - containerPort: 5432
    volumeMounts:
    - name: postgres-storage
      mountPath: /var/lib/postgresql/data
  volumes:
  - name: postgres-storage
    persistentVolumeClaim:
      claimName: postgres-pvc