apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-ssd
provisioner: rancher.io/local-path
parameters:
  hostPath: "/mnt/disks/ssd"
reclaimPolicy: Delete
volumeBindingMode: waitForFirstConsumer
allowVolumeExpansion: true