apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - image: mohamed1780/vote
          name: vote
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: vote
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
        - image: mohamed1780/vote-ui
          name: vote-ui
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: vote-ui
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
      

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
spec:
  type: NodePort
  ports:
    - name: "vote-ui-service"
      port: 80
      targetPort: 80
      nodePort: 30001
    - name: "vote-service"
      port: 5000
      targetPort: 5000
  selector:
    app: vote